// screen.availWidth()
// 1920
// screen.width()
// 1920
// screen.availHeight()
// 1055
// screen.pixelDepth()
// 24
// screen.color()
// //undefined
// screen.colorDepth()
// 24
// screenX
// 639
// screen.isExtended()
// true
// screen.isExtended()
// true
// screen.isExtended()
// false
// screen.color()
// //undefined
// screen.orientation()
// // ScreenOrientation {angle: 0, type: 'landscape-primary', onchange: null}angle: 0onchange: nulltype: "landscape-primary"[[Prototype]]: ScreenOrientationangle: (...)lock: ƒ lock()onchange: (...)type: (...)unlock: ƒ unlock()constructor: ƒ ScreenOrientation()Symbol(Symbol.toStringTag): "ScreenOrientation"get angle: ƒ angle()get onchange: ƒ onchange()set onchange: ƒ onchange()get type: ƒ type()[[Prototype]]: EventTarget
